### ISSUE TITLE
(triton-third-party) Azure-storage-cpplite dependency will not build with tag 0.3.0

### ISSUE THREAD

**Issue by alexraymond** [triton-inference-server/server#4002]
**Description**
When building Triton (client) from source with Clang 11, the build will fail at the triton-third-party step because of an issue with azure-storage-cpplite.

`azure-storage-cpplite/src/azure-storage-cpplite/src/base64.cpp:108:28: error: no member named 'runtime_error' in namespace 'std'`

This is caused by a missing `#include <stdexcept>` in their repository. It has been fixed in [this commit](https://github.com/Azure/azure-storage-cpplite/commit/a3a9c21de3fa9932dcfceb2b6617757a511c75c3). Unfortunately, this is not covered by the tag `0.3.0` used in the `third-party` subrepo.

One way of circumventing the issue in my case was to update the `GIT_TAG` of azure-storage-cpplite dependency to `origin/master`. 

**Triton Information**
Building triton-inference-client from SHA f0f2b89b3b8418a0a79a8dd60329a8b99489268b.

**To Reproduce**
Build triton-inference-client from source with Clang 11 + Ubuntu 20.

**Comment by dyastremsky** [comment]
We will investigate. Can you please provide reproduction instructions, error output, and logs? We regularly build from source in our CI runs, so it may be a version mismatch on a library or driver.

**Comment by jbkyang-nvi** [comment]
Hi @alexraymond can you list the steps it took you to build the client? I don't see `azure-storage-cpplite` needed in the clients... I have tried building with the 22.02 min container with Clang 11 and there were no errors. I have a branch `kyang-patch-azure-third-party` that adds the specific commit you need but I want to make sure that it is in fact, what you need.

**Comment by alexraymond** [comment]
Hi there,

Here are the steps I took, from a clean clone of the client repo:
```
mkdir build && cd build
cmake -DCMAKE_INSTALL_PREFIX=`pwd`/install -DTRITON_ENABLE_CC_GRPC=ON -DTRITON_ENABLE_CC_HTTP=ON -DTRITON_ENABLE_PERF_ANALYZER=OFF -DTRITON_ENABLE_EXAMPLES=OFF -DTRITON_ENABLE_TESTS=OFF ../
make
```

Here is a complete log. 
[client-build-log.txt](https://github.com/triton-inference-server/server/files/8232464/client-build-log.txt)

**Comment by jbkyang-nvi** [comment]
@alexraymond can you instead do `make cc-clients python-clients java-clients` instead of just running make?

**Comment by jbkyang-nvi** [comment]
Hi @alexraymond can you try ^^ again. Also the README states:
```
...
Then use make to build the clients and examples.

$ make cc-clients python-clients java-clients
...
```
It is the way to build Triton client.

**Comment by alexraymond** [comment]
You are right. _This is the way._
I was able to adapt my setup to run with `make cc-clients` as part of the build. I can close this issue now.
